//
// Created by Joe Ayoub on 14/11/24 at 15:40.
//

#ifndef INC_2024_PROJECT_JOE_AYOUB_UA_ENTITY_VIEW_H
#define INC_2024_PROJECT_JOE_AYOUB_UA_ENTITY_VIEW_H


class Entity_View {

};


#endif //INC_2024_PROJECT_JOE_AYOUB_UA_ENTITY_VIEW_H
