//
// Created by Joe Ayoub on 16/11/24 at 20:04.
//

#ifndef INC_2024_PROJECT_JOE_AYOUB_UA_CONTROLLER_H
#define INC_2024_PROJECT_JOE_AYOUB_UA_CONTROLLER_H


class Controller {

};


#endif //INC_2024_PROJECT_JOE_AYOUB_UA_CONTROLLER_H
